import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses';

const sesClient = new SESClient({
  region: process.env.AWS_REGION || 'us-east-1'
});

const DEFAULT_FROM = process.env.SES_FROM_EMAIL || 'noreply@caasdiglobal.in';

const escapeHtml = (value) =>
  String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');

const interpolate = (template, values = {}) => {
  if (!template) return '';

  let output = template;
  Object.entries(values).forEach(([key, value]) => {
    const regex = new RegExp(`{{\\s*${key}\\s*}}`, 'g');
    output = output.replace(regex, String(value ?? ''));
  });

  return output;
};

const defaultSubjectByTemplate = {
  'task-created': 'Task Created: {{taskName}}',
  'status-updated': 'Status Updated: {{taskName}} is now {{taskStatus}}',
  'approval-request': 'Approval Requested: {{taskName}}',
  custom: 'Workflow Notification: {{workflowName}}'
};

const defaultBodyByTemplate = {
  'task-created': [
    'A workflow has created a new task.',
    '',
    'Workflow: {{workflowName}}',
    'Task: {{taskName}}',
    'Status: {{taskStatus}}',
    'Timestamp: {{timestamp}}'
  ].join('\n'),
  'status-updated': [
    'A workflow has updated task status.',
    '',
    'Workflow: {{workflowName}}',
    'Task: {{taskName}}',
    'Status: {{taskStatus}}',
    'Timestamp: {{timestamp}}'
  ].join('\n'),
  'approval-request': [
    'A workflow requires your approval.',
    '',
    'Workflow: {{workflowName}}',
    'Task: {{taskName}}',
    'Current Status: {{taskStatus}}',
    'Timestamp: {{timestamp}}'
  ].join('\n'),
  custom: [
    'Workflow notification',
    '',
    'Workflow: {{workflowName}}',
    'Task: {{taskName}}',
    'Status: {{taskStatus}}',
    'Timestamp: {{timestamp}}'
  ].join('\n')
};

const buildHtml = ({ subject, body, values }) => {
  const safeSubject = escapeHtml(subject);
  const safeLines = String(body || '')
    .split('\n')
    .map((line) => `<p style="margin:0 0 10px 0; color:#334155; font-size:14px; line-height:1.6;">${escapeHtml(line)}</p>`)
    .join('');

  return `
<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="padding:24px 0;background:#f8fafc;">
      <tr>
        <td align="center">
          <table role="presentation" cellpadding="0" cellspacing="0" width="620" style="max-width:620px;width:100%;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
            <tr>
              <td style="background:linear-gradient(135deg,#0f766e 0%,#115e59 100%);padding:20px 24px;">
                <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:700;">Workflow Notification</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:24px;">
                <h2 style="margin:0 0 16px 0;color:#0f172a;font-size:18px;font-weight:600;">${safeSubject}</h2>
                ${safeLines}
                <hr style="border:none;border-top:1px solid #e2e8f0;margin:16px 0;" />
                <p style="margin:0;color:#64748b;font-size:12px;">Generated by workflow: ${escapeHtml(values.workflowName || '')}</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
};

export const sendWorkflowEmail = async ({
  to,
  subject,
  body,
  templateType = 'custom',
  variables = {}
}) => {
  if (!to) {
    throw new Error('Email recipient is required');
  }

  const mergedValues = {
    workflowName: variables.workflowName || 'Workflow',
    taskName: variables.taskName || variables.name || 'Task',
    taskStatus: variables.taskStatus || variables.status || 'N/A',
    timestamp: variables.timestamp || new Date().toISOString(),
    ...variables
  };

  const baseSubject = subject || defaultSubjectByTemplate[templateType] || defaultSubjectByTemplate.custom;
  const baseBody = body || defaultBodyByTemplate[templateType] || defaultBodyByTemplate.custom;

  const resolvedSubject = interpolate(baseSubject, mergedValues);
  const resolvedBody = interpolate(baseBody, mergedValues);
  const resolvedHtml = buildHtml({ subject: resolvedSubject, body: resolvedBody, values: mergedValues });

  const command = new SendEmailCommand({
    Source: `Caasdi Workflows <${DEFAULT_FROM}>`,
    Destination: { ToAddresses: [to] },
    Message: {
      Subject: { Data: resolvedSubject, Charset: 'UTF-8' },
      Body: {
        Text: { Data: resolvedBody, Charset: 'UTF-8' },
        Html: { Data: resolvedHtml, Charset: 'UTF-8' }
      }
    }
  });

  const result = await sesClient.send(command);

  return {
    success: true,
    messageId: result.MessageId,
    to,
    from: DEFAULT_FROM,
    subject: resolvedSubject
  };
};
